<a href="https://colab.research.google.com/github/JoshiAbhishek866/Python-and-ML-work/blob/main/Email_Spam_classification_using_Multinomial_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import Libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
#load the data
from google.colab import files
uploaded = files.upload( )

Saving emails.csv to emails.csv


In [ ]:
#Read the CSV file
df=pd.read_csv('emails.csv')

#Print the first 5 rows of data
df.head(5)

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [ ]:
#Print the shape (get the numbers of columns and rows)
df.shape

(5172, 3002)

In [ ]:
#Get the columns name of the data set
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [ ]:
#check for duplicates and remove them
df.drop_duplicates(inplace=True)

In [ ]:
#show the new shape (number of rows and columns)
df.shape

(5172, 3002)

In [ ]:
#show the number of missing (NAN,NaN,na) data for each column
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [ ]:
#download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(text):
  #1 remove puntuation
  #2 remove stopwords
  #3 return  a list of clean text words

  #1
  nopunc = [char for char in text if char not in string.puntuation]
  nopunc =' '.join(nopunc)

  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

In [ ]:
import string

def process_text(text):
    # Convert text to string if it's not already
    if not isinstance(text, str):
        text = str(text)

    # Remove punctuation
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)

    # Split text into tokens
    tokens = nopunc.split()

    return tokens

# Showing tokenization (list of tokens)
df['text'].head().apply(process_text)


0    [0]
1    [0]
2    [0]
3    [0]
4    [0]
Name: text, dtype: object

In [ ]:
#Example

message4= 'hello world hello hello world play'
message5= 'test test test test one hello'
print(message4)
print()

#convert the text to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow4 =  CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)
print()

print(bow4.shape)

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

(2, 5)


In [ ]:
#convert collection of text to a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [ ]:
#split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size=0.20, random_state= 0)

In [ ]:
#shape of messages_bow
messages_bow.shape

(5172, 6)

In [ ]:
#create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [ ]:
#Print the  predictions
print(classifier.predict(X_train))

#print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 1 0 0]


In [ ]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred= classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print()
print('Accuracy: \n', accuracy_score(y_train, pred))
print()

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4078
           1       0.00      0.00      0.00        49
           2       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         2

    accuracy                           0.99      4137
   macro avg       0.20      0.20      0.20      4137
weighted avg       0.97      0.99      0.98      4137


Confusion Matrix: 
 [[4078    0    0    0    0]
 [  49    0    0    0    0]
 [   5    0    0    0    0]
 [   3    0    0    0    0]
 [   2    0    0    0    0]]

Accuracy: 
 0.9857384578196761




/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Print the  predictions
print(classifier.predict(X_test))

#print the actual values
print(y_test.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [ ]:
#Evaluate the model on the testing data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred= classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy: \n', accuracy_score(y_test, pred))
print()

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1026
           1       0.00      0.00      0.00         8
           3       0.00      0.00      0.00         1

    accuracy                           0.99      1035
   macro avg       0.33      0.33      0.33      1035
weighted avg       0.98      0.99      0.99      1035


Confusion Matrix: 
 [[1026    0    0]
 [   8    0    0]
 [   1    0    0]]

Accuracy: 
 0.991304347826087



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
